.\simplify.exe input_rectangle_with_two_holes.csv 11 > my_output_rectangle_with_two_holes.txt
.\simplify.exe input_cushion_with_hexagonal_hole.csv 13 > my_output_cushion_with_hexagonal_hole.txt
.\simplify.exe input_blob_with_two_holes.csv 17 > my_output_blob_with_two_holes.txt
.\simplify.exe input_wavy_with_three_holes.csv 21 > my_output_wavy_with_three_holes.txt
.\simplify.exe input_lake_with_two_islands.csv 17 > my_output_lake_with_two_islands.txt
.\simplify.exe input_original_01.csv 99 > my_output_original_01.txt
.\simplify.exe input_original_02.csv 99 > my_output_original_02.txt
.\simplify.exe input_original_03.csv 99 > my_output_original_03.txt
.\simplify.exe input_original_04.csv 99 > my_output_original_04.txt
.\simplify.exe input_original_05.csv 99 > my_output_original_05.txt
.\simplify.exe input_original_06.csv 99 > my_output_original_06.txt
.\simplify.exe input_original_07.csv 99 > my_output_original_07.txt
.\simplify.exe input_original_08.csv 99 > my_output_original_08.txt
.\simplify.exe input_original_09.csv 99 > my_output_original_09.txt
.\simplify.exe input_original_10.csv 99 > my_output_original_10.txt